part of 'expense_model.dart';

// This file is usually auto-generated by build_runner and Hive.
// Ensure that the `build_runner` command is fixed in your environment to avoid manually updating this file.
